### ISSUE TITLE
How to get a Kalman filtering angle around the y-axis

### ISSUE THREAD

**Issue by ffffire0316** [ElectronicCats/mpu6050#39]
How to get a Kalman filtering angle around the y-axis，I don't know much about it

**Comment by Arthulisher** [comment]
Hello @ffffire0316  

Thanks for contacting the ElectronicCats support team

Since this question is related to general ElectronicCats project-based queries, we recommend you to post it on the Arduino forum, and search it on the Web. since queries like this can be answered by many people and different solutions can be explored. 

Have success on your projects
Best regards...
