### ISSUE TITLE
Initialization in z-axis reversal leads to P reversal in PID for pitch and roll

### ISSUE THREAD

**Issue by Zhaosn** [ElectronicCats/mpu6050#77]
I'd like to share my solution to an issue similar to this one #55  and point out a bug I seem it be.

**Describe the bug**
The problem is this: my pitch and roll will overshoot in the reverse direction (e.g. when I turn an axis from 11 to -22, the value may go to 55 and then slowly change back to -22 (the closer it gets to -22 the slower it changes)) I tried different CalibrateAccel() and CalibrateGyro() parameters and it doesn't fix.

**To Reproduce**
Yesterday I tried the example/MPU6050_DMP6 in v1.3.0 and still had this problem. 

> I found out today that when I initialize the mpu6050 module with the Z-axis pointing to the sky there is no problem. ✅

> And my previous initialization of the module with the z-axis pointing downwards triggered the bug every time.❗

so I guess maybe when I initialized with the z-axis pointing downwards the P in the PID for pitch and roll didn't go negative resulting in the response changing to positive feedback at first.

**To help us to understand your situation, we would like to ask you for the following additional information::**
 - esp8266 nodemcu
 - Windows 11
 - platformIO installed a few days ago
 - The problem triggers steadily when the z-axis is initialized downwards, I'm buying other mpu6050 modules to exclude hardware issues, but just initialize the z-axis facing upwards and there's no problem!

**Comment by AndreaZGuz** [comment]
Hi @Zhaosn  !

Thank you for sharing this information and your experience.

In past days a similar issue was discussed. The origin is how the module works internally, due to the MEMS. The module can only read the position for two axes simultaneously, while the third one approximates the value.

Here you will find a good explanation about it [#74](https://github.com/ElectronicCats/mpu6050/issues/74#issuecomment-1894903761).

The behavior is expected, as long as the readings get stable afterwards. 

Do not hesitate to reach out again in case you face any new issues o questions on this library.
